export const GET_LIST_FEATURE = "GET_LIST_FEATURE";
export const ADMIN_LOGIN = "ADMIN_LOGIN";
export const GET_LIST_TEAM = "GET_LIST_TEAM";
export const GET_INFO_COMPANY = "GET_INFO_COMPANY";

export const GET_LIST_CUSTOMER = "GET_LIST_CUSTOMER";
export const POST_INFO_CUSTOMER = "POST_INFO_CUSTOMER";

export const GET_SERVICES = "GET_SERVICES";
export const GET_PROJECTS = "GET_PROJECTS";
export const GET_PRICES = "GET_PRICES";
export const EDITTEAM = "EDITTEAM";
export const POSTTEAM = "POSTTEAM";
export const GETCUSTOMER = "GETCUSTOMER";
export const GET_BLOG = "GET_BLOG";

export const GET_CATEGORY_PROJECTS = "GET_CATEGORY_PROJECTS";
export const EDIT_CATEGORY_PROJECTS = "EDIT_CATEGORY_PROJECTS";
export const EDIT_SERVICE = "EDIT_SERVICE";
export const DELETE_SERVICE = "DELETE_SERVICE";
