export const GET_LIST_FEATURE = "GET_LIST_FEATURE";
export const ADMIN_LOGIN = "ADMIN_LOGIN";
export const GET_LIST_TEAM = "GET_LIST_TEAM";

export const GET_LIST_COMPANY = "GET_LIST_COMPANY";
export const ADD_COMPANY_API = "ADD_COMPANY_API";
export const EDIT_COMPANY_API = "EDIT_COMPANY_API";
export const EDIT_COMPANY = "EDIT_COMPANY";
export const EDITCOMPANY = "EDITCOMPANY";
export const DELETE_COMPANY_API = "DELETE_COMPANY_API";

export const GET_LIST_CUSTOMER = "GET_LIST_CUSTOMER";
export const POST_INFO_CUSTOMER = "POST_INFO_CUSTOMER";

export const GET_SERVICES = "GET_SERVICES";
export const GET_PROJECTS = "GET_PROJECTS";
export const GET_PRICES = "GET_PRICES";
export const EDITTEAM = "EDITTEAM";
export const POSTTEAM = "POSTTEAM";
export const GETCUSTOMER = "GETCUSTOMER";
export const GET_BLOG = "GET_BLOG";
export const ADD_BLOG_API = "ADD_BLOG_API";
export const EDIT_BLOG_API = "EDIT_BLOG_API";
export const EDIT_BLOG = "EDIT_BLOG";
export const EDITBLOG = "EDITBLOG";
export const DELETE_BLOG_API = "DELETE_BLOG_API";

export const GET_CATEGORY_PROJECTS = "GET_CATEGORY_PROJECTS";



// 
export const LOADDINGADMIN ="LOADDINGADMIN"
export const EDIT_CATEGORY_PROJECTS = "EDIT_CATEGORY_PROJECTS";
export const EDIT_SERVICE = "EDIT_SERVICE";
export const DELETE_SERVICE = "DELETE_SERVICE";
export const ADD_SERVICE = "ADD_SERVICE";
export const UPDATE_SERVICE = "UPDATE_SERVICE";
export const UPDATE_CATEGORY_PROJECTS = "UPDATE_CATEGORY_PROJECTS";
